language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - cd segregatedFeesSite
  - npm install
  - npm test
  - npm run build
deploy:
  provider: s3
  access_key_id: AWS_KEY_ID
  secret_access_key: AWS_KEY_SECRET
  bucket: "uwec-segregated-fees"
  skip_cleanup: true
  acl: public_read
